ecommerce/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.paginaPrincipal, name="home"),
    path('showmore/',  views.showmoreView, name='show_more'),
    path('contacto/', views.paginaContacto, name="contacto"),
    path('carrito/', views.pagincaCarrito, name="carrito"),

    path('update/<int:product_id>/' , views.update_product, name='update_product'),
    path('create/', views.create_product, name='create_product'),
    path('createUser/', views.create_user, name='create_user'),
    
    path('editUser/<int:user_id>/', views.edit_user, name='edit_user'),

    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('deleteUser/<int:user_id>/', views.delete_user, name='delete_user'),
    path('producto/<int:selectedValue>/', views.paginaContacto, name="contacto"),
    

    path('filtroInicio/<int:selectedValue>/', views.filtroInicio, name='filtroInicio'),
    path('filtroPrecio/<int:selectedPrize>/', views.filtroPrecio, name='filtroPrecio'),
    path('filtroProveedor/<int:selectedProveedor>/', views.filtroProveedor, name='filtroProveedor'),
    
    path('descProducto/<int:productId>/', views.descripcionProducto, name='descripcionProducto'),
    #path('', views.filtroInicio, name='filtroInicio'),

    path('login/', views.iniciarSesion, name="login"),
    path('registro/', views.registrarse, name="registro"),
    path('logout/', views.logoutUser, name="logout"),
    path('pwdRecovery/', views.cambiarPwd, name="passwordRecovery"),
    path("perfil/", views.perfilUsuario, name="perfil"),

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart_detail/',views.cart_detail,name='cart_detail'),

    path('albaran/<int:pedido_id>/', views.generate_albaran_pdf, name='generate_albaran_pdf'),
    path('etiqueta/<int:pedido_id>/', views.generate_etiqueta_pdf, name='generate_etiqueta_pdf'),
    path('update_order_status/<int:order_id>/<int:status_id>/', views.update_order_status, name='update_order_status'),

    path('cart/mandarPedido/<str:tipo_envio>/<str:transportista>/', views.mandarPedido, name='mandarPedido'),
    #path('cart/mandarPedido/', views.mandarPedido, name='mandarPedido'),
    path("delete_order/<int:order_id>/", views.delete_order, name="delete_order"),
    path('update_order_status/<int:order_id>/<int:status_id>/', views.update_order_status, name='update_order_status'),
    path('createRelation/<int:proveedor>/<int:producto>/', views.createRelation, name='createRelation'),
    path('eliminar_producto_pedido/<int:product_id>/', views.delete_product_proveedor, name='eliminar_producto_pedido'),
    ]

warehousewars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
]

ecommerce/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractUser
from phonenumber_field.validators import ValidationError
# validate_international_phonenumber por ahora no se usa tengo que ver como hacerlo para poner la extension sin que de error.
class User(AbstractUser):

    # null true = la BBDD puede tener este campo vacio
    # blank true = se puede dejar vacio en el formulario
    email = models.EmailField(unique=True) # con esto se indica que el login sea con email, ya no se pueden repetir
    telefono = models.CharField(max_length=15, validators=[ValidationError], null=True, blank=True)
    adress = models.CharField(max_length=250, null=True, blank=True)
    cpostal = models.CharField(max_length=10, null=True, blank=True)
    role_id = models.IntegerField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Transportistas(models.Model):
    id_trans = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'Transportistas'

class Albaranes(models.Model):
    albaran_id = models.AutoField(primary_key=True)
    pedido = models.ForeignKey('Pedidos', on_delete=models.CASCADE)
    date = models.DateField()
    id_seguimiento = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'Albaranes'


class Estados(models.Model):
    status_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'Estados'


class Pedidos(models.Model):
    pedido_id = models.AutoField(primary_key=True)
    date_order = models.DateField()
    status = models.ForeignKey(Estados,on_delete=models.CASCADE)
    total_cost = models.FloatField()
    user= models.ForeignKey('User',on_delete=models.CASCADE)
    address = models.CharField(max_length=25)
    cpostal = models.CharField(max_length=10)
    total_weight =  models.FloatField()
    isUrgent = models.BooleanField()
    transportista = models.ForeignKey(Transportistas,on_delete=models.CASCADE)
    arrival_date = models.DateField()
    total_products = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Pedidos' 


class Productos(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)
    stock = models.IntegerField()
    min_stock = models.IntegerField()
    price = models.FloatField()
    location = models.CharField(max_length=25)
    image = models.ImageField(upload_to='products/')
    product_description = models.CharField(max_length=25, blank=True, null=True)
    type = models.ForeignKey('Tipos',on_delete=models.CASCADE)
    fecha_llegada = models.DateField(blank=True, null=True)
    weight = models.FloatField()
    isRestock = models.BooleanField()


    class Meta:
        managed = False
        db_table = 'Productos'

class PedidoProductos(models.Model):
    product_id = models.ForeignKey(Productos, on_delete=models.CASCADE, db_column='product_id')  
    pedido_id = models.ForeignKey(Pedidos, on_delete=models.CASCADE, db_column='pedido_id')
    quantity = models.IntegerField()
    total_cost = models.FloatField()

    class Meta:
        managed = False
        db_table = 'PedidoProductos'

class ProveedorProducto(models.Model):
    provprod_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    product_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Proveedor-Producto'


class Roles(models.Model):
    role_id = models.AutoField(primary_key=True)
    role_name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'Roles'


class Tipos(models.Model):
    type_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'Tipos'


class Usuarios(models.Model):
    user_id = models.AutoField(primary_key=True)
    role = models.ForeignKey(Roles,on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25, blank=True, null=True)
    email = models.CharField(max_length=25)
    address = models.CharField(max_length=25, blank=True, null=True)
    phone_number = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Usuarios'

ecommerce/views.py
import random
from django.utils import timezone
from django.shortcuts import render, redirect
from django.db import connection, transaction
import json
from django.http import JsonResponse
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
#from django.contrib.auth.models import User
from ecommerce.models import User, Albaranes, Pedidos, Estados, Tipos
from .funciones import *
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from .models import Estados, PedidoProductos, Pedidos, Productos, ProveedorProducto, Transportistas, Usuarios

from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO
from django.http import FileResponse
from django.http import Http404

from rest_framework.decorators import api_view
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.db.models import F, Prefetch
from django.core.mail import EmailMessage

from datetime import datetime, timedelta
from django.shortcuts import get_object_or_404


def vistaAlmacen(request):
    if 'active_tab' not in request.session:
        request.session['active_tab'] = 'CRUDproduct'

    if request.GET.get('active_tab'):
        request.session['active_tab'] = request.GET.get('active_tab')

    columnaProduct = request.GET.get('columna')
    directionProduct = request.GET.get('direction')
    query_product_name = request.GET.get("query_product_name")
    query_product_locate = request.GET.get("query_product_locate")
    query_product_id = request.GET.get("query_product_id")
    query_product_stock_min = request.GET.get("query_product_stock_min")
    query_product_stock_max = request.GET.get("query_product_stock_max")
    query_product_min_stock_min = request.GET.get("query_product_min_stock_min")
    query_product_min_stock_max = request.GET.get("query_product_min_stock_max")
    query_product_price_min = request.GET.get("query_product_price_min")
    query_product_price_max = request.GET.get("query_product_price_max")

    columnaUser = request.GET.get('columnaUser')
    directionUser = request.GET.get('directionUser')
    query_id_user = request.GET.get('query_id_user')
    query_nombre_user = request.GET.get('query_nombre_user')
    query_apellido_user = request.GET.get('query_apellido_user')
    query_correo_user = request.GET.get('query_correo_user')
    query_direccion_user = request.GET.get('query_direccion_user')
    query_telefono_user = request.GET.get('query_telefono_user')
    query_roleId_user = request.GET.get('query_roleId_user')

    columnaPedido = request.GET.get('columnaPedido ')
    directionPedido  = request.GET.get('directionPedido ')
    query_pedido_id = request.GET.get('query_pedido_id')
    query_pedido_statusId = request.GET.get('query_pedido_statusId')
    query_pedido_price_min = request.GET.get('query_pedido_price_min')
    query_pedido_price_max = request.GET.get('query_pedido_price_max')
    query_pedido_userId = request.GET.get('query_pedido_userId')
    query_pedido_address = request.GET.get('query_pedido_address')
    query_pedido_transport = request.GET.get('query_pedido_transport')

    columnaPedidoProv = request.GET.get('columnaPedidoProv')
    directionPedidoProv  = request.GET.get('directionPedidoProv')
    query_orderProv_provProdId = request.GET.get('query_orderProv_provProdId')
    query_orderProv_userId = request.GET.get('query_orderProv_userId')
    query_orderProv_productId = request.GET.get('query_orderProv_productId')

    columnaPedidoProd = request.GET.get('columnaPedidoProd')
    directionPedidoProd  = request.GET.get('directionPedidoProd')
    query_PedProd_product = request.GET.get('query_PedProd_product')
    query_PedProd_pedido = request.GET.get('query_PedProd_pedido')
    query_PedProd_quantity = request.GET.get('query_PedProd_quantity')
    query_PedProd_total_cost_min = request.GET.get('query_PedProd_total_cost_min')
    query_PedProd_total_cost_max = request.GET.get('query_PedProd_total_cost_max')

    
    if columnaProduct and directionProduct:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "Productos" ORDER BY {columnaProduct} {directionProduct}')
        product = dictfetchall(cursor)
    else:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "Productos"')
        product = dictfetchall(cursor)

    if columnaUser and directionUser:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "ecommerce_user" ORDER BY {columnaUser} {directionUser}')
        user = dictfetchall(cursor)
    else:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "ecommerce_user"')
        user = dictfetchall(cursor)

    if columnaPedido and directionPedido:
        cursor = connection.cursor()
        cursor.execute(f'SELECT p.*, s.name as status_name, s.status_id as status_status_id, t.name as transportista_name FROM "Pedidos" p JOIN "Estados" s ON p.status_id = s.status_id JOIN "Transportistas" t ON p.transportista_id = t.id_trans ORDER BY {columnaPedido} {directionPedido}')
        order = dictfetchall(cursor)
    else:
        cursor = connection.cursor()
        cursor.execute(f'SELECT p.*, s.name as status_name, s.status_id as status_status_id, t.name as transportista_name FROM "Pedidos" p JOIN "Estados" s ON p.status_id = s.status_id JOIN "Transportistas" t ON p.transportista_id = t.id_trans')
        order = dictfetchall(cursor)
    
    if columnaPedidoProv and directionPedidoProv:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "Proveedor-Producto" ORDER BY {columnaPedidoProv} {directionPedidoProv}')
        orderProv = dictfetchall(cursor)
    else:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "Proveedor-Producto"')
        orderProv = dictfetchall(cursor)

    if columnaPedidoProd and directionPedidoProd:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "PedidoProductos" ORDER BY {columnaPedidoProd} {directionPedidoProd}')
        pedidoProd = dictfetchall(cursor)
    else:
        cursor = connection.cursor()
        cursor.execute(f'SELECT * FROM "PedidoProductos"')
        pedidoProd = dictfetchall(cursor)

    if query_product_name: #chars
        product = [p for p in product if query_product_name in p['name']]
    if query_product_locate: #chars
        product = [p for p in product if query_product_locate in p['location']]
            
    if query_product_id: #Int
        product = [p for p in product if p['id'] == int(query_product_id)]
    
    if query_product_stock_min and query_product_stock_max:
        product = [p for p in product if p['stock'] >= int(query_product_stock_min) and p['stock'] <= int(query_product_stock_max)]

    if query_product_stock_min:
        product = [p for p in product if p['stock'] >= int(query_product_stock_min)]

    if query_product_stock_max:
        product = [p for p in product if p['stock'] <= int(query_product_stock_max)]    

    if query_product_min_stock_min and query_product_min_stock_max:
        product = [p for p in product if p['min_stock'] >= int(query_product_min_stock_min) and p['min_stock'] <= int(query_product_min_stock_max)]

    if query_product_min_stock_min:
        product = [p for p in product if p['min_stock'] >= int(query_product_min_stock_min)]

    if query_product_min_stock_max:
        product = [p for p in product if p['min_stock'] <= int(query_product_min_stock_max)]  

    if query_product_price_min and query_product_price_max:
        product = [p for p in product if p['price'] >= float(query_product_price_min) and (p['price']) <= float(query_product_price_max)]

    if query_product_price_min:
        product = [p for p in product if p['price'] >= float(query_product_price_min)]

    if query_product_price_max:
        product = [p for p in product if p['price'].replace("$","") <= float(query_product_price_max)]  

    if query_nombre_user: #chars
        user = [p for p in user if query_nombre_user in p['first_name']]

    if query_apellido_user: #chars
        user = [p for p in user if query_apellido_user in p['last_name']]

    if query_correo_user: #chars
        user = [p for p in user if query_correo_user in p['email']]
    
    if query_direccion_user: #chars
        user = [p for p in user if query_direccion_user in p['adress']]

    if query_telefono_user: #chars
        user = [p for p in user if query_telefono_user in p['telefono']]

    if query_roleId_user: #chars
        user = [p for p in user if p['role_id'] == int(query_roleId_user)]

    if query_id_user: #chars
        user = [p for p in user if p['id'] == int(query_id_user)]

    if query_pedido_id: #chars
        order = [p for p in order if p['pedido_id'] == int(query_pedido_id)]
    
    if query_pedido_statusId: #chars
        order = [p for p in order if p['status_id'] == int(query_pedido_statusId)]

    if query_pedido_userId: #chars
        order = [p for p in order if p['user_id'] == int(query_pedido_userId)]
   
    if query_pedido_address: #chars
        order = [p for p in order if query_pedido_address in p['address']]
    
    if query_pedido_transport: #chars
        order = [p for p in order if p['transportista_id'] == int(query_pedido_transport)]

    if query_pedido_price_min and query_pedido_price_max:
        order = [p for p in order if float(p['total_cost'].replace("$", "")) >= float(query_pedido_price_min) and float((p['total_cost']).replace("$","")) <= float(query_pedido_price_max)]

    if query_pedido_price_min:
        order = [p for p in order if float(p['total_cost'].replace("$","")) >= float(query_pedido_price_min)]

    if query_pedido_price_max:

ecommerce/templates/ecommerce/albaranPedido.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Albarán {{ albaran.albaran_id }}</title>
  <style>
    @page {
      size: A5;
      margin: 1cm;
    }

    body {
      font-family: Arial, sans-serif;
      font-size: 14px;
    }

    .content {
      width: 100%;
      max-width: 14cm;
      margin: 0 auto;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .header .logo {
      width: 150px;
      height: auto;
      background-image: none;
    }

    .header .company-info {
      text-align: right;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    table, th, td {
      border: 1px solid black;
      padding: 3px;
      text-align: left;
    }

    th {
      font-weight: bold;
      background-color: #f2f2f2;
    }

    .text-center {
      text-align: center;
    }

    .signature {
      display: flex;
      justify-content: space-between;
      margin-top: 30px;
      flex-wrap: wrap;
    }

    .signature_item {
      flex-basis: calc(50% - 10px);
      border: 2px solid black;
      padding: 10px;
      height: 100px;
      margin-bottom: 20px;
    }

    .signature_item p {
      font-weight: bold;
      margin-bottom: 10px;
    }


  </style>
</head>
<body>
  <div class="content">
    <div class="header">
      <div class="logo">
        <img src="{{ image_path }}" alt="Logo de la empresa SlotsSolutions" style="width: 150px;">
      </div>
      <div class="company-info">
        <br>
        Teléfono: 660 142 089<br>
        Dirección: C/ Doctor García Tapia, 13 Madrid<br>
        Correo: suport@slotsolutions.com
      </div>
    </div>

    <h3>Albarán id: {{ albaran.albaran_id }}</h3>
    <table>
      <tr>
        <th>Pedido Id</th>
        <th>Fecha</th>
        <th>ID de seguimiento</th>
        <th>Dirección de entrega</th>
      </tr>
      <tr class="text-center">
        <td style="margin-left: 35px;">{{ albaran.pedido.pedido_id }}</td>
        <td style="margin-left: 10px;">{{ albaran.date }}</td>
        <td style="margin-left: 25px;">{{ albaran.id_seguimiento }}</td>
        <td>{{ albaran.pedido.address }}</td>
      </tr>
    </table>

    <div class="signature-container">
      <div class="signature-item">
          <p style="margin-top: 40px;">Firma del transportista: <strong>{{ albaran.pedido.transportista.name }}</strong> </p>
          <br>
          <br>
          <br>
          <br>
      </div>
      <div class="signature-item">
          <p>Firma del operario de SlotsSolutions:</p>
          <div class="signature-sello"></div>
      </div>
    </div>
    
    </div>
    </body>
</html>

ecommerce/templates/ecommerce/cambiarPwd.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

{% for msg in messages %}
{% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger fade show" role="alert">
	<strong>{{msg}}</strong>
</div>
{% endif %}
{% endfor %}

<div class="main">
    <div class="nav-item col-md-4 col-xs-12">
        <form class="formularioInicio" method="POST" action="">
            {% csrf_token %}

            <div class="navbar-brand logo-contenedor" href="#">
                <img src="{% static 'images/SlotsSolutions.jpg' %}" alt="SlotsSolutions" class="logo">
              </div>

              <h2 style="text-align: center;">Cambio de contraseña</h2>

              <ul class="navbar-nav ml-auto distancia">
                    <li class="nav-item"><b>CORREO</b></li>
                    <li class="nav-item"><input class="textfields" name="email" placeholder="Inserte su correo"></input></li>
                    <li class="nav-item distancia"><b>NUEVA CONTRASEÑA</b></li>
                    <li>
                        <li class="nav-item"><input class="textfields" type="password" name="password" placeholder="Constraseña"></input></li>
                    </li>
                    <li class="nav-item"><input class="textfields distancia" type="password" name="password2" placeholder="Repita la contraseña"></input></li>
                    <li class="nav-item distancia"><input type="submit" class="botoniniciar" value="Restaurar contraseña"/></li>
              </ul>
            </form>
    </div>
</div>

{% endblock content %}

ecommerce/templates/ecommerce/perfil.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
{% load filtros %}

<script>
    function mostrarDatosPedido(id) {
        var contenido = document.getElementById("detallePedido"+id);
        contenido.classList.toggle('perfilHide');
    }
</script>

<section class="color-grey">
    <section class="container"  style="height: 600px;">
        <div class="container-fluid" style="height: 500px;">
            <!-- Parte superior -->
            <div class="row py-5">
                <div class="col-12 text-center">
                    <h1>{{ user.first_name }}</h1>
                    <hr>
                </div>
            </div>

            <!-- Parte inferior -->
            <div class="row" >
                <!-- Parte izquierda -->
                <div class="col-lg-3 col-sm-12 bg-light">
                    <div class="list-group mt-3">
                        <a href="#" id="selectDatos" class="list-group-item list-group-item-action active">Datos</a>
                        {%if request.user.role_id == 3%}
                        <a href="#" id="selectPedidos" class="list-group-item list-group-item-action">Pedidos</a>
                        {%endif%}
                    </div>
                </div>
                <!-- Parte derecha -->
                <div class="col-lg-9 col-sm-12" style = "height: 400px; max-height: 450px ; overflow: auto; ">
                    <!-- Información de datos -->
                    <div id="infoDatos">
                        <h2>Datos del perfil</h2>
                        <p>Nombre: {{ user.first_name }}</p>
                        <p>Correo electrónico: {{ user.email }}</p>
                        <p>Teléfono: {{ user.telefono }}</p>
                        <p>Dirección: {{ user.address }}</p>
                        <p>Código postal: {{ user.cpostal }}</p>
                    </div>
                    {%if request.user.role_id == 3%}
                    <!-- Información de pedidos -->
                    <div id="infoPedidos" class="perfilHide">
                        <h2>Información de pedidos</h2>
                        
                        {% for pedido in pedidos %}
                        <div class="border pedidos mt-3">
                            <div id="datosPedido{{ pedido.pedido_id }}" class="pedidos boreder p-2 mb-2" style="cursor: pointer;" onclick="mostrarDatosPedido('{{ pedido.pedido_id }}')">
                                <div class="row">
                                <div class="col-lg-3 ">
                                    <p>Direcci&oacute;n de env&iacute;o:</p>
                                    <p style="margin-top: -15px;">{{ pedido.address }}</p>
                                </div>
                                <div class="col-lg-3">
                                    <p>ID del pedido:</p>
                                    <p style="margin-top: -15px;">{{ pedido.pedido_id }}</p>
                                </div>
                                <div class="col-lg-3 text-center">
                                    <p>Precio final: </p>
                                    <p style="margin-top: -15px;">{{ pedido.total_cost }}€</p>
                                </div>
                                <div class="col-lg-3 text-center">
                                    <p>Estado del pedido: </p>
                                    <p style="margin-top: -15px; font-weight: bold;">{{ pedido.status.name }}</p>
                                </div>
                            </div>
                            </div>
                            <div id="detallePedido{{ pedido.pedido_id }}" class="pedidos-detail perfilHide">                                
                                <!-- Información de los productos del pedido -->
                                <h5 class="pl-3">Detalles adicionales:</h5>
                                
                                <div class="row">
                                    <p class="col-lg-3">Transportista: <strong>{{ pedido.transportista.name }}</strong></p>

                                    {% if pedido.isUrgent %}
                                        <p class="col-lg-4">Tipo de env&iacute;o: <strong>Urgente</strong></p>
                                    {% else %}
                                        <p class="col-lg-4">Tipo de env&iacute;o: <strong>Normal</strong></p>
                                    {% endif %}


                                
                                {% if pedido.transportista.name == "SEUR" %}
                                        <p class="col-lg-5">D&iacute;a de entrega: {{ pedido.arrival_date }}</strong></p>
                                    </div>
                                    <div class="row">
                                        <p class="col-lg-12">Peso pedido (gramos): <strong>{{ pedido.total_weight }}</strong></p>
                                    </div>
                                {% elif pedido.transportista.name == "DHL" %}
                                        <p class="col-lg-5">Fecha del pedido: <strong>{{ pedido.date_order }}</strong></p>
                                    </div>
                                {% else %}
                                        <p class="col-lg-5">Fecha del pedido: <strong>{{ pedido.date_order }}</strong></p>
                                    </div>
                                    <div class="row">
                                        <p class="col-lg-6">Peso pedido (gramos): <strong>{{ pedido.total_weight }}</strong></p>
                                        <p class="col-lg-6">Cantidad de unidades: {{ pedido.total_products }}</p>
                                    </div>
                                    <div class="row">
                                        <p class="col-lg-12">C&oacute;digo postal de la entrega: {{ user.cpostal }}</p>
                                    </div>
                                {% endif %}
                                
                                <h5 class="pl-3">Productos del pedido:</h5>
                                {%  for item in pedido.pedidoproductos_set.all %}
                                    <div class="row p-3">
                                        <div class="col-lg-3 col-sm-12">
                                            <img src={{ item.product_id.image.url|slice:'1:'|urldecode }} alt="{{ item.producto.name }}" style="width: 100px; height: 100px;">
                                        </div>
                                        <div class="col-lg-6 col-sm-12">
                                            <p style="font-weight: bold;"> {{ item.product_id.name }}</p>
                                            <p style="margin-top: -10px;">{{ item.quantity }} x {{ item.product_id.price }} € = {{ item.total_cost }}€</p>
                                        </div>
                                        <div class="col-lg-1 col-sm-12">
                                            <button class="btn btn-danger">Cancelar</button>
                                        </div>
                                       
                                    </div>
                                <hr style="width: 85%; margin-top: -5px;">
                                {% endfor %}
                               

                            </div>
                        </div>
                        {% endfor %}
                   
                    </div>   
                    {%endif%}                                
                </div>
            </div>
        </div>
    </section>
</section>
{% endblock content %}